### ISSUE TITLE
Google analytics tags aren't set up properly

### ISSUE THREAD

**Issue by uncomplete** [tarrex/online-resume#14]
Hey,

Thanks for creating this.

I noticed the google analytics tag wasn't being populated.

Just need to change `{{ site.google_analytics }}` to `{{ site.analytics.google }}` in the _includes/head.html file.

Same for Cloudflare.

**Comment by uncomplete** [comment]
See here: https://github.com/uncomplete/uncomplete.github.io/commit/b953e84992a6f8371439ed3b7f8382577386a0ad

**Comment by tarrex** [comment]
Thank you for pointing out this issue. I ignored it when I modified it before, it has been fixed now.
