### ISSUE TITLE
Error in CI Jekyll Scss

### ISSUE THREAD

**Issue by walexaindre** [tarrex/online-resume#19]
**After fork this project with default data I get the following error in Github Actions:**

  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    end of file reached
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------

**Using trace generates no meaningful data:**

  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    end of file reached
/usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `readbyte': end of file reached (EOFError)
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `block in read'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `loop'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `read'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/connection.rb:62:in `block in read'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/connection.rb:61:in `synchronize'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/connection.rb:61:in `read'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:76:in `receive_proto'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:19:in `block (2 levels) in initialize'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:18:in `loop'
	from /usr/gem/gems/sass-embedded-1.66.1-x86_64-linux-musl/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
Error: Process completed with exit code 1.

   
**Note: Looking in other recent forks (<1 month), I see the same error.** 

_Can you rerun the github actions to see if that happens on the main branch?_

**Comment by tarrex** [comment]
Thanks for your issue. Unfortunately I didn't reproduce this issue built it locally or forked it using another account.

GitHub provides two ways to build and deployment. You can find it in `settings -> Pages -> Build and deployment -> Source` section. One is the classic `Deploy from a branch`, with this way of deploying, GitHub will use the built-in(maybe) CI, and the other is through `Github Actions`, which is still a Beta version, and can be deployed through your own Github Actions.

I have always used the first way to build and deploy site. The purpose of the Github Actions I provide in this project is not to deploy the project to GitHub Pages, but to validate that there are no errors. Anyway, my previous Github Actions also need to be upgraded, I will upgrade the Github Actions a bit. You can try it by selecting `Deploy from a branch` option.

I hope this can help you fix this issue. If you have any questions, feel free to ask.
