### ISSUE TITLE
如何在netlify部署

### ISSUE THREAD

**Issue by ghost** [tarrex/online-resume#2]
netlify内报错，log显示缺少gemfile

**Comment by tarrex** [comment]
The default files `Gemfile` and `Gemfile.lock` is removed. It's OK on Github, but not on the platform that needs to configure the jekyll environment from scratch, like netlify. So if you want deploy on this platform, you could create a `Gemfile` yourself in the project root directory with the following content:

```
source "https://rubygems.org"
gem "jekyll", "~> 4.2.2"
```
